name: Deploy to Render

on:
  push:
    branches:
      - main  # or specify the branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Set these in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t abubakarshahzad/flaskimage:latest .  # Tag the image as latest
          docker push abubakarshahzad/flaskimage:latest         # Push the latest tag

      - name: Deploy to Render
        run: |
          curl -X POST \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Content-Type: application/json" \
          -d '{"serviceId": "srv-crg6h4tsvqrc73evbv90", "clearCache": false}' \
          https://api.render.com/v1/services/srv-crg6h4tsvqrc73evbv90/deploys
